### DISCUSSION TITLE
Adjustable font size for admin panel

### DISCUSSION THREAD

**Discussion by zatakiya** [payloadcms/payload#10294] [Feature Requests & Ideas]
Some users finds font-size on admin panel too small. It would be a nice addon to make it adjustable. 

A new Font Size field can be added under Payload Settings in admin panel's account view (Below Admin Theme field.)

Sharing UI idea for multi-step font size selector.
![image](https://github.com/user-attachments/assets/f2961d63-841d-4686-ba71-40b1b093919c)

**Comment by chaotic-justice** [comment]
need this too, need to make the font size smaller than `normal text`

**Comment by immotus** [comment]
Alternatively, you can simply change the font size (and most other visual properties) through your `custom.scss`:

```css
:root
{
	--font-body: GitLabSans, system-ui;
	--font-mono: GitLabMono, monospace;
	--font-serif: GitLabSans, serif;
	--font-body-size: 16px;
	--font-body-size--sm: 14px;
}
```
