### DISCUSSION TITLE
How to style .doc-header individually?

### DISCUSSION THREAD

**Discussion by openbayou** [payloadcms/payload#10918] [Q&A] [answered]
Hello,
Why is it that .doc-header, where the title of post, can't be style for individually? If I want to hide the title in .doc-header, it's hidden across all pages.

![Untitled-19](https://github.com/user-attachments/assets/8dbc6d69-cc8c-4cbd-8469-f6ea1bb4a698)

**Comment by akhrarovsaid** [comment, marked as answer]
Hey @openbayou,

Try adding this to your `custom.scss` located in your `(payload)` folder:

```css
div.doc-header:has(+ .collection-edit--posts) {
  display: none;
}
```

**Reply by openbayou** [reply]
.doc-header is outside ..collection-edit--posts

**Reply by akhrarovsaid** [reply]
> Didn't work.

> .doc-header is outside ..collection-edit--posts

@openbayou I have it open as we speak to a collection with slug posts. I have the above custom scss applied. It works on my end. Are you sure you're putting it into `app/(payload)/custom.scss`? Whether or not the header is outside collection-edit is kind of irrelevant, that is what the `:has(+ ...)` is for anyway. Double check on your end please.

The only reason I can see why this wouldn't work for you is if you are developing somewhere that `:has` is not supported (like IE11).

![image](https://github.com/user-attachments/assets/fbd3dec5-2bde-4bc2-86f0-df28732bccfc)

If you want it to only target the `h1` (as I have in the image above) then do this:

```css
div.doc-header:has(+ .collection-edit--posts) > h1 {
  display: none;
}
```
