### DISCUSSION TITLE
How to Connect to MongoDB During Docker Build for PayloadCMS + NextJs Deployment on a Single VPS?

### DISCUSSION THREAD

**Discussion by only-issues** [payloadcms/payload#12634] [Q&A]
Hello, I am trying to deploy PayloadCMS + NextJs + MongoDB on the same VPS using Docker, but I encountered an issue: during the build process, it needs to connect to MongoDB, however the Dockerfile does not have the MongoDB network. What should I do?

`docker-compose.prod.yml`:
```yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env.production
    networks:
      - internal
    volumes:
      - media:/app/media

  mongodb:
    image: mongo:8
    command:
      - --auth
    networks:
      - internal
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: mongo --quiet --eval "db.adminCommand('ping')" -u ${MONGO_USER} -p ${MONGO_PASS} --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

volumes:
  mongo_data:
  media:
networks:
  internal:
    driver: bridge
```

`Dockerfile`:
```yml
# To use this Dockerfile, you have to set `output: 'standalone'` in your next.config.mjs file.
# From https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

FROM node:22-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1
ENV IS_BUILD yes
RUN \
  if [ -f yarn.lock ]; then yarn run build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Remove this line if you do not have this folder
COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD HOSTNAME="0.0.0.0" node server.js
```

`.env.production`:
```
MONGO_USER="xxxxxxxxxxxxxxxxxxxxxxx"
MONGO_PASS="xxxxxxxxxxxxxxxxxxxxxxx"
MONGO_DB="comic_web"
DATABASE_URI="mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}?authSource=admin"

PAYLOAD_SECRET="316f8ff5xxxxxxxxxxxxxxxx"
PAYLOAD_CONFIG_PATH="src/payload.config.ts"

NEXT_PUBLIC_SERVER_URL="http://localhost:3000"
```

Error:
```
11.72 > cross-env NODE_OPTIONS=--no-deprecation next build
11.72
16.57 Attention: Next.js now collects completely anonymous telemetry regarding usage.
16.58 This information is used to shape Next.js' roadmap and prioritize features.
16.58 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
16.58 https://nextjs.org/telemetry
16.58
16.86    ▲ Next.js 15.3.3
16.86    - Environments: .env.production
16.86    - Experiments (use with caution):
16.86      ✓ typedRoutes
16.86
17.11    Creating an optimized production build ...
224.3  ✓ Compiled successfully in 3.4min
224.3    Linting and checking validity of types ...
245.8    Collecting page data ...
266.9    Generating static pages (0/10) ...
270.1    Generating static pages (2/10)
270.1    Generating static pages (4/10)
[09:19:18] ERROR: Error: cannot connect to MongoDB. Details: getaddrinfo EAI_AGAIN mongodb
299.2     err: {
299.2       "type": "C",
299.2       "message": "getaddrinfo EAI_AGAIN mongodb",
299.2       "stack":
299.2           MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb
299.2               at H (/app/.next/server/chunks/5108.js:241:50445)
299.2               at L.openUri (/app/.next/server/chunks/5108.js:241:57582)
299.2               at async Object.tl [as connect] (/app/.next/server/chunks/5108.js:280:5632)
299.2               at async tJ.init (/app/.next/server/chunks/5108.js:373:17369)
299.2       "reason": {
299.2         "type": "Unknown",
299.2         "servers": {
299.2           "mongodb:27017": {
299.2             "address": "mongodb:27017",
299.2             "type": "Unknown",
299.2             "hosts": [],
299.2             "passives": [],
299.2             "arbiters": [],
299.2             "tags": {},
299.2             "minWireVersion": 0,
299.2             "maxWireVersion": 0,
299.2             "roundTripTime": -1,
299.2             "minRoundTripTime": 0,
299.2             "lastUpdateTime": 28205097,
299.2             "lastWriteDate": 0,
299.2             "error": {},
299.2             "topologyVersion": null,
299.2             "setName": null,
299.2             "setVersion": null,
299.2             "electionId": null,
299.2             "logicalSessionTimeoutMinutes": null,
299.2             "maxMessageSizeBytes": null,
299.2             "maxWriteBatchSize": null,
299.2             "maxBsonObjectSize": null,
299.2             "primary": null,
299.2             "me": null,
299.2             "$clusterTime": null,
299.2             "iscryptd": false
299.2           }
299.2         },
299.2         "stale": false,
299.2         "compatible": true,
299.2         "heartbeatFrequencyMS": 10000,
299.2         "localThresholdMS": 15,
299.2         "setName": null,
299.2         "maxElectionId": null,
299.2         "commonWireVersion": 0,
299.2         "logicalSessionTimeoutMinutes": null
299.2       }
299.2     }
299.3  ⨯ Next.js build worker exited with code: 1 and signal: null
299.4  ELIFECYCLE  Command failed with exit code 1.
```
