### DISCUSSION TITLE
Docker compose file for production erros

### DISCUSSION THREAD

**Discussion by parthapaul7** [payloadcms/payload#1595] [Q&A] [answered]
I am facing lot of issues in the production of with docker-compose
here is my docker-compose.yml file 

```
version: '3'`

services:

  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - media:/home/node/app/media
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn build && yarn serve"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: production 
      PAYLOAD_SECRET: TESTING

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
  media:
```

it is showing errors like this 
```
cms-payload-1  | $ yarn copyfiles && yarn build:payload && yarn build:server
cms-payload-1  | $ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
cms-payload-1  | /bin/sh: copyfiles: not found
cms-payload-1  | error Command failed with exit code 127.
```
Docker is working fine in development mode with `yarn dev`
