### DISCUSSION TITLE
Problems with deploying with docker

### DISCUSSION THREAD

**Discussion by SuddenDev** [payloadcms/payload#170] [Q&A] [answered]
Hi Everyone,

I'm trying to deploy payload with docker to a DigitalOcean Droplet. I push it to my gitlab ci/cd runner, which builds the docker image and then saves it to the container registry (also gitlab). I then pull the image on my droplet, which uses caddy 2 as my reverse proxy. I can access the api on my computer, but aparently, the admin panel can not.

This is my .env file on local, that I then override with docker env vars.
```
NODE_ENV=dev
ENVIRONMENT=dev
PORT=3000
PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000

MONGODB_URI=<redacted URI>
PAYLOAD_SECRET=<redacted secret>
PAYLOAD_LICENCE=<redacted licence>
```

On production I use the same, except PAYLOAD_PUBLIC_SERVER_URL
```
PAYLOAD_PUBLIC_SERVER_URL=https://cms.dtampe.com
```

When I try to access `https://cms.dtampe.com/admin`, it stucks at loading and I get the following error:
`Failed to load resource: net::ERR_CONNECTION_REFUSED        http://localhost:3000/api/users/me`

This works though, so I really don't know where I went wrong. `https://cms.dtampe.com/api/pages`

I did already read through Issues and Discussions, but can't seem to figure it out. I also tried to use the next.js template or this repo here [https://github.com/joshhills/joshhills-site](https://github.com/joshhills/joshhills-site), but to no avail.

My Docker FIle:
```
Dockerfile


From node:14-alpine
WORKDIR ./app
COPY package*.json  ./
RUN npm install
COPY . . 
RUN npm run build
#RUN rm -f .env
EXPOSE 3000
CMD ["npm", "start"]
```

gitlab ci
```
.gitlab-ci.yml


# This file is a template, and might need editing before it works on your project.
# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.
docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  environment:
    name: production
    url: https://cms.dtampe.com
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "Running now docker build"
    - echo "$PAYLOAD_PUBLIC_SERVER_URL"
    - echo "$NODE_ENV"
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

```

I'd be greatful for any hints!
Cheers!
