### DISCUSSION TITLE
Documenting running Payload using the Azure CosmosDB Emulator docker image mongoDB API

### DISCUSSION THREAD

**Discussion by DanRibbens** [payloadcms/payload#4162] [General]
I just went through the job of setting up a local emulation of cosmos db using the MongoDB API and am writing it here to document the process.

1. Created a new payload app using `npx create-payload-app@latest`, choosing mongodb as the Database and whatever other options.
1. Edit the docker-compose.yml to have: 
```yml
services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb
    tty: true
    restart: always
    ports:
      - '8081:8081'
      - '10250:10250'
      - '10255:10255'
    volumes:
      - data:/data/db
    logging:
      driver: none
    environment:
      - AZURE_COSMOS_EMULATOR_ENABLE_MONGODB_ENDPOINT=4.2
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true

volumes:
  data:
  node_modules:
```
3. Download the .pem key from `https://localhost:8081/_explorer/emulator.pem` and save locally in the project
3. In the .env file I used the following connection string `DATABASE_URI=mongodb://localhost:C2y6yDjf5%2FR%2Bob0N8A7Cgv30VRDJIWEHLM%2B4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw%2FJw%3D%3D@localhost:10255/admin?tls=true&tlsCertificateKeyFilePassword=C2y6yDjf5%2FR%2Bob0N8A7Cgv30VRDJIWEHLM%2B4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw%2FJw%3D%3D&tlsAllowInvalidCertificates=true&retrywrites=false`
4. Edit the payload.config.ts adding `indexSortableFields: true`.
