### DISCUSSION TITLE
Docker production and PAYLOAD_PUBLIC vars

### DISCUSSION THREAD

**Discussion by mat-twg** [payloadcms/payload#5002] [Q&A]
Hi all! I'm trying to use **PAYLOAD_PUBLIC** variables with docker in **production** mode. In the examples of docker builds given in the documentation, everything works fine, but only in **development** mode.

**Case**: 
- Build docker image
- Setting the date format from an environment variable for a container in **production** via **docker-compose**.
```shell
dateFormat: process.env.PAYLOAD_PUBLIC_DATE_FORMAT || 'MMMM do yyyy, h:mm a',
```

**Problem**: after building a docker image without variables **PAYLOAD_PUBLIC** is not applied

_How to solve:_

**Possible usage**: docker-compose example
```yaml
version: '3.9'

services:
  payload:
    image: registry.io/example/prod
    ports:
      - '3000:3000'
    volumes:
      - uploads:/home/node/app/uploads
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      DATABASE_URI: mongodb://mongo/example
      PAYLOAD_SECRET: e5db5b614cf485b00ea2a453
      # DateTime format
      PAYLOAD_PUBLIC_DATE_FORMAT: "dd MMMM yyyy at hh:mm"
      
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  uploads:
  data:
```

I would like to discuss an example implementation with you

```sh
#!/bin/sh

# entrypoint.sh

echo "Build to update PAYLOAD_PUBLIC variables."

yarn build

export PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js

exec "$@"
```

```dockerfile
# Dockerfile
FROM node:18.8-alpine as base
WORKDIR /home/node/app
COPY . .

FROM base as dev
ENV NODE_ENV development
RUN yarn install
CMD ["yarn", "dev"]

FROM base as prod
ENV NODE_ENV production
RUN yarn install --frozen-lockfile --production
ENTRYPOINT ["sh", "entrypoint.sh"]
CMD ["node", "dist/server.js"]
```

How it works: Build docker image with target **prod** and run docker-compose with this image

The only thing that confuses me is that I have to build a project every time the container starts, maybe this is not critical.. what do you think about this?

```shell
# LOG
Build to update PAYLOAD_PUBLIC variables.
yarn run v1.22.19
$ cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles
$ cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload build
$ tsc --project tsconfig.server.json
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png,js}" dist/
Done in 16.81s.
[23:24:18] INFO (payload): Connected to MongoDB server successfully!
[23:24:18] INFO (payload): Starting Payload...
[23:24:18] INFO (payload): Payload Admin URL: 
[23:24:18] INFO (payload): Swagger URL: /api/doc/
[23:24:18] INFO (payload): App URL:
```
--
refs:
https://github.com/payloadcms/payload/discussions/3758
https://github.com/payloadcms/payload/issues/4892
