### DISCUSSION TITLE
Docker Installation Documentation

### DISCUSSION THREAD

**Discussion by etmartinkazoo** [payloadcms/payload#594] [Feature Requests & Ideas]
# Documentation Issue

Having a succinct set of instructions for using Docker with Payload CMS seems advantageous. The folks at Directus have a really nice example of this https://docs.directus.io/getting-started/installation/docker/

## Additional Details

I am by no means a Docker guru but would be happy to work on this with some others.

**Comment by jmikrut** [comment]
Hey @etmartinkazoo — we'll tackle this soon in an official manner and also add some Docker functionality directly within `create-payload-app`.

I'm going to move this to a discussion and tag it as a Feature Request!

**Reply by etmartinkazoo** [reply]
@jmikrut - That is great news. If you need anyone to help review/test, I'd be happy to offer a hand. I'm using Payload CMS with a few projects right now coupled with Eleventy.js on the frontend with some serverless functions; it has been a dynamite combination. Really exited for the future of Payload CMS.

**Reply by DanRibbens** [reply]
I am so thrilled that you are enjoying Payload! 
If you're able to share an 11ty + Payload boilerplate that would be a big help, we would like to make more starters repos available.

**Reply by etmartinkazoo** [reply]
> 

@jmikrut - We've got a nice solution for Payload CMS with Docker working now both locally and in production. Also, we have a software company - [Brem](https://brem.io) - 30 minutes south of you all in Kalamazoo. It'd be great to meet up sometime.

**Comment by denolfe** [comment]
The latest version of create-payload-app will create a docker-compose file that is ready to use for development 🎉

Here is what it looks like if you're wanting to adapt it to an existing project:

```
version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
```
