### DISCUSSION TITLE
Unable to launch payload after successful docker installation

### DISCUSSION THREAD

**Discussion by saidhasyim** [payloadcms/payload#6333] [Q&A]
Hello,

I was able to sucessfully run payload container without error. Payload container log shows:
```
Run `npm audit` for details.
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8081
  http://192.168.240.3:8081
Hit CTRL-C to stop the server
```

I installed it using docker-compose. This is my docker-compose file.
```
version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/ubuntu/payload
      - node_modules:/home/node/app/node_modules
    working_dir: /home/ubuntu/payload/
    command: sh -c "npm install && npm start"
    depends_on:
      - mongo
    environment:
      DATABASE_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: production
      PAYLOAD_SECRET: xxxxxxxxx
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
```
Note, I edited the command to use `npm` instead of `yarn`.

As you can see from the container log, there is no error. But, I cannot launch the payload using these:
http://localhost:3000/admin 
http://localhost:3000
http://localhost:8081/admin 
http://localhost:8081

It just loads infinitely and at the end it would just say no page found.

There is no error in the container log, too.
