### DISCUSSION TITLE
Lexical: Allow customizing Fonts

### DISCUSSION THREAD

**Discussion by tyteen4a03** [payloadcms/payload#8210] [Feature Requests & Ideas]
Lexical allows for changing the font of the text; would be great if Payload allowed customization in this aspect too.

**Comment by AndKenneth** [comment]
I think this might actually be a bug, there is actually a way to add classes to the nodes in the lexical editor, but whenever I do this it won't let me change normal text (which seems to be a serifed font by default) - only headers and the like. Tried poking around to figure it out but didn't get very far, but there's a pretty complex set of CSS that gets applied so it's hard to track down.

**Comment by immotus** [comment]
You can already do that through your custom CSS. This is how I do it.

```css
.rich-text-lexical .editor-shell
{
	font-family: var(--font-body) !important;
	font-weight: 300 !important;
}

.link-editor .link-input a
{
	color: var(--accent) !important;
	font-size: 14px !important;
}

.link-editor .link-input a:hover
{
	color: var(--accent) !important;
}

.LexicalEditorTheme__link
{
	color: var(--accent) !important;
}
```
