### ISSUE TITLE
Payload generates a down migration where it drops payload_migrations and tries to delete a record there

### ISSUE THREAD

**Issue by allohamora** [payloadcms/payload#11882]
### Describe the Bug

Payload generates a down migration where it drops payload_migrations and tries to delete a record there.

<img width="1250" alt="Image" src="https://github.com/user-attachments/assets/d576fae2-59d9-4b4f-86d5-1f4a04286664" />

<img width="1275" alt="Image" src="https://github.com/user-attachments/assets/c90aa3e6-6e98-4376-837e-cbc49da55847" />

https://github.com/payloadcms/payload/blob/4fc2eec301c10661938ba3b6c952aa62116441ec/packages/drizzle/src/migrateDown.ts#L53-L60

.env
```env
DATABASE_URI=postgres://app:example@localhost:5432/app
```

docker-compose.yml
```yml
services:
  pg:
    image: postgres:16.2
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

```

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/tree/6b56343b97c2e8aa8818b53a77d7d4dc8eac4986/templates/with-postgres

### Reproduction Steps

Generate an initial migration:
```bash
npm run payload migrate:create
```
Apply this migration:
```bash
npm run payload migrate
```

Down this migration:
```bash
npm run payload migrate:down
```

### Which area(s) are affected? (Select all that apply)

db-postgres

### Environment Info

```text
Payload: 3.31.0
Next: 15.2.3
Node: 22.13.0
Postgresql image: 16.2
```
