### ISSUE TITLE
Not a nice scroll when using a lot of tabs in collection

### ISSUE THREAD

**Issue by Kikky** [payloadcms/payload#1259]
# Bug Report

If we have a lot of tabs - UI is not very user friendly :)

![ui](https://user-images.githubusercontent.com/614922/195854479-69f92fde-4390-4215-86f2-2b415558a21d.png)

## Steps to Reproduce
Just add a lot of tab fields to collection.

## Detailed Description
Payload version: 1.1.11
Browser: latest Chrome

**Comment by jmikrut** [comment]
Hey @Kikky thanks for the report! The horizontal overflow is intended, and is modeled after a common UI pattern that is seen more and more online, even in Google apps, where a list of labels just overflows and allows X-scroll. 

I did add some CSS to hide that big scrollbar, but on second thought, I actually think that the scrollbar should remain, even as ugly as it looks. If you feel like your "overflowing" tabs are too commonly needed and that this is interrupting your admin UX, I'd try and figure out how to reduce them. But for us, whenever we have this many tabs, we just accept that we did this intentionally and that some horizontal scrolling will be necessary.

If you want to hide the scrollbar, you can add the following CSS to your project:

```css
.tabs-field {
  &__tabs-wrap {
    -ms-overflow-style: none;
    scrollbar-width: none;

    &::-webkit-scrollbar {
      display: none;
    }
  }
}
```

That will hide the big scrollbar but then your admin editors won't be able to scroll if they don't have a trackpad. 

Another thing you could do is allow tab names to wrap by adding the following CSS:

```css
.tabs-field {
  &__tabs-button {
    white-space: initial;
    flex-shrink: initial;
  }
}
```

This will make some pretty crazy looking tab names, and I actually prefer the overflow, but this might be better for your use case. Here's an example of what this looks like:

![image](https://user-images.githubusercontent.com/6651896/195865405-574289a5-93fd-42f1-b0fc-8690559b4a30.png)
