### ISSUE TITLE
Error installing sharp 

### ISSUE THREAD

**Issue by binaryhubio** [payloadcms/payload#1303]
# Bug Report

Sharp error: "Cannot find module '.../build/Release/sharp-linux-arm64v8.node'"

## Current Behavior

I am running payload cms inside nestjs in a docker image FROM 'node:18'. It used to work but suddenly I am getting this sharp error (I am running on an M1 max processor) - but it used to work...

## Expected Behavior

To build correctly

## Possible Solution

Not sure, I spent 4 hours on this matter and no success.

## Steps to Reproduce

1. Run payload inside a Dockerfile that has "FROM node:18" on an m1 machine.
2. Not sure if it matters but I am using payload inside nestjs (again, it used to work...)
3. You will get sharp library error

## Detailed Description

<img width="704" alt="Screenshot 2022-10-27 at 23 30 17" src="https://user-images.githubusercontent.com/28837903/198392371-b32a6775-0773-4bda-b753-7c9bbba5cb00.png">

**Comment by jmikrut** [comment]
Hey @binaryhubio — this is actually an issue with Sharp and Docker rather than Payload. We've run into this before and there are some helpful issues / threads out there that can help you fix this.

https://github.com/lovell/sharp/issues/2875
https://github.com/lovell/sharp/issues/1990
https://github.com/lovell/sharp/issues/2815

I'm going to close this for now but we do have an official `docker-compose` file that now ships with `create-payload-app`:

@denolfe can you share that `docker-compose` file here and then close the issue?

**Comment by denolfe** [comment]
Here is the working docker-compose.yml. Modify as needed.

```
version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
```
