### ISSUE TITLE
Collapsible child row field div margin-bottom

### ISSUE THREAD

**Issue by DavidOliver** [payloadcms/payload#1649]
Payload 1.3.0.

At narrow viewport widths, this SCSS (which I believe is intended to avoid "double" spacing on the last field in a collapsible field):

```scss
.collapsible-field {
  // ...

  .field-type:last-child {
    margin-bottom: 0;
  }
}
```

results in the last field in a row in a callapsible having no margin-bottom at narrow viewport widths:

![image](https://user-images.githubusercontent.com/192853/207098547-2d5f6b64-b477-4df3-a8ac-0a9ffa878983.png)

When the viewport is wider, fields that are not last-child in a row still result in doubling up of spacing:

![image](https://user-images.githubusercontent.com/192853/207100465-e92beea0-07e6-435c-9280-5947dd2b5c0f.png)

I haven't checked how they display, but the `blocks` and `array` fields seem to use:

```scss
  &__fields>.field-type:last-child {
    margin-bottom: 0;
  }
```

However, based on a look in the HTML inspector in-browser, collapsible fields don't seem to have a `.collapsible__fields` element.

---

Could fields that act as containers/groupings of other fields perhaps have their `__content` elements' padding-bottom set to 0 so that inner fields don't have to have their margin-bottom varied based on context?
