### ISSUE TITLE
Minor bug in admin ui - media items per page in media collection

### ISSUE THREAD

**Issue by hades200082** [payloadcms/payload#2133]
# Bug Report

When viewing media collections the paging is incorrect and leaves empty slots.

![image](https://user-images.githubusercontent.com/1023581/219955009-da7add58-49f4-419c-8ac9-819dca2ab31b.png)

## Steps to Reproduce

1. Upload media to payload
2. View the media collection listing page in admin

## Other Details

The "per page" options need to be different for media libraries to ensure that a full page is shown at all responsive breakpoints. Simply adding 2 to the current options if its a media collection would suffice.

**Comment by DanRibbens** [comment]
Thanks for reporting!

You are right this is a bug, but it is not one we are going to fix. We are planning to remove this separate list view for upload collections and instead use the table component.

In the future we will have other list view options. For now we can close the issue and move towards the single view.

**Comment by dominikzogg** [comment]
@DanRibbens is there a way to show the upload (when) its an image as preview in the list view? So its regognizable in the list view?

**Comment by DanRibbens** [comment]
> @DanRibbens is there a way to show the upload (when) its an image as preview in the list view? So its regognizable in the list view?

I'm not sure I understand the question @dominikzogg. The list view shows a preview of images in a thumbnail size. Are you saying that is too small for your use?

You can make that larger by applying some custom CSS if you wish. We wrote this up for an enterprise client who asked this question so I'll share it for you also.

If you haven't done any custom css in your Payload app, you can see how from the docs: https://payloadcms.com/docs/admin/customizing-css#adding-your-own-css-scss

Then you can use these scss options below.

Here is the Payload default styles for reference, in your case you don't want images cropping this way.

![before-any-styles](https://github.com/payloadcms/payload/assets/6434612/38769a40-5849-4d90-91fa-86922a1b88a5)

## Contain
Keeps square dimensions of base(3) x base(3) while preserving the original aspect ratio of image
```css
.table {
  .file {
    .thumbnail {
      img, svg {
        object-fit: contain;
      }
    }
  }
}
```

![after-with-contain](https://github.com/payloadcms/payload/assets/6434612/3d87c841-0bbc-4c2d-8794-41d9e2cab24e)


## Contain with max width
If square dimensions are not desired then &__thumbnail could be changed to whatever desired height or width & while preserving the original aspect ratio of image
```css
.table {
  .file {
    &__thumbnail {
      // display: inline-block; Already exists
      max-width: base(6); // Originally base(3) - this can be changed to whatever is needed
      // height: base(3); Already exists
    }

    .thumbnail {
      img, svg {
        object-fit: contain;
      }
    }
  }
}
```

![after-with-contain-and-max-width](https://github.com/payloadcms/payload/assets/6434612/6c201270-1721-4753-b093-91ea9acc0ce5)
