### ISSUE TITLE
Lexical plugin imports CSS

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#4085]
### Link to reproduction

private repo

### Describe the Bug

We are using the following code to convert rich text data from Slate to Lexical. This allows us to prepare the SSR React serializer before we fully migrate to Lexical. However, the Lexical plugin imports CSS code from Payload admin UI.

```TS
import { type SlateNode, convertSlateToLexical, defaultSlateConverters } from '@payloadcms/richtext-lexical';

/**
 * Convert Slate rich text data to Lexical.
 *
 * @param data
 * @returns
 */
export default function convertSlateToLexicalFormat(data: SlateNode[]) {
    if (data && Array.isArray(data) && !('root' in data)) {
        return convertSlateToLexical({
            converters: defaultSlateConverters,
            slateData: data
        });
    }

    return data;
}
```

We are seeing this CSS code which collides with our Bootstrap code:

```CSS
a.btn {
  display: inline-block;
}

.btn {
  background: transparent;
  line-height: 1.9230769231rem;
  border-radius: 4px;
  font-size: 1rem;
  margin-top: 1.9230769231rem;
  margin-bottom: 1.9230769231rem;
  border: 0;
  cursor: pointer;
  font-weight: normal;
  text-decoration: none;
  text-align: center;
  color: inherit;
}
```

We just want to use the data model conversion without any other side effects.

Could you please export the lexical module from the Payload Lexical plugin and all needed types? Otherwise we have to install an NPM package and will end in versioning conflicts with different Lexical versions.

### To Reproduce

Use the provided code in Next.js server component and check bundled CSS.

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb, bundler-webpack, live-preview
