### ISSUE TITLE
@import url("./test.css") does not work within css files

### ISSUE THREAD

**Issue by JarrodMFlesch** [payloadcms/payload#4310]
### Link to reproduction

N/A

### Describe the Bug

If you are using css instead of scss, importing `css` files into your main file does not work.

Error output:
```
Error: Can't resolve 'test.css' in '/path-to-project/node_modules/payload/dist/admin/scss'
    at finishWithoutResolve (/path-to-project/node_modules/enhanced-resolve/lib/Resolver.js:369:18)
```

The workaround for now is to use `scss` files, which works as expected.

### To Reproduce

```ts
// file: payload.config.ts

import { webpackBundler } from '@payloadcms/bundler-webpack'
import { mongooseAdapter } from '@payloadcms/db-mongodb'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import path from 'path'
import { buildConfig } from 'payload/config'

export default buildConfig({
  admin: {
    bundler: webpackBundler(),
    css: path.resolve(__dirname, './css/styles.css'),
  },
  collections: [],
  db: mongooseAdapter({
    url: process.env.DATABASE_URI,
  }),
  editor: lexicalEditor(),
})
```

```css
/* file: css/styles.css */

@import url("./test.css")
```

```css
/* file: css/test.css */

body {
  background-color: red;
}
```

### Payload Version

2.2.2

### Adapters and Plugins

@payloadcms/bundler-webpack

**Comment by JarrodMFlesch** [comment]
Font files are also unable to be imported unless they are in the top level file.

**Comment by JarrodMFlesch** [comment]
I think the way forward here is to provide your own custom webpack alias, this will allow files to be found when imported within inside of the `admin/scss/app.scss` file.

Here is an example:

```ts
// file: payload.config.ts

import { webpackBundler } from '@payloadcms/bundler-webpack'
import { mongooseAdapter } from '@payloadcms/db-mongodb'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import path from 'path'
import { buildConfig } from 'payload/config'

export default buildConfig({
  admin: {
    bundler: webpackBundler(),
    css: path.resolve(__dirname, './css/styles.css'),
        webpack: (config) => ({
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config?.resolve?.alias,
          '~css': path.resolve(__dirname, './css'),
         // ^^ this line
        },
      },
    }),
  },
  collections: [],
  db: mongooseAdapter({
    url: process.env.DATABASE_URI,
  }),
  editor: lexicalEditor(),
})
```

```css
/* file: css/styles.css */

@import '~css/test.css';
```

```css
/* file: css/test.css */

body {
  background-color: red;
}
```

This will fix the inability to import font files as well, for example:

```css
/* file: css/fonts.css */

@font-face {
  font-family: 'YourFontName';
  src: url('~css/my-font.woff') format('woff2');
  font-weight: normal;
  font-style: normal;
}
```
