### ISSUE TITLE
Ecommerce template: Incorrect type generation for `db-postgres` adapter potentially causing invalid field errors

### ISSUE THREAD

**Issue by abe123442** [payloadcms/payload#4885]
### Describe the Bug

The type of any collection item is `number | Item` (`Item` is some arbitrary type) when using Postgres as the database. The Payload templates all rely on the fact that an item is of type `string | Item`.

In the Ecommerce template, Payload gives the following error after a payment has been completed -
![image](https://github.com/payloadcms/payload/assets/44077482/2ab9711c-b755-4e52-8532-2d413e43cd16)
![image](https://github.com/payloadcms/payload/assets/44077482/d34a4a28-7017-43ba-a46a-f62a275d6e67)
even after regenerating types and the graphql schema. I am unsure if these two problems are related to each other, but at the moment, this and other templates are tailored to work with MongoDB only. 

Also, when creating the payment intent, it would be helpful if the currency of the intent was the same as that of the product.

### To Reproduce

1. `npx create-payload-app@latest ecommerce -t ecommerce`
2. Choose Postgres as your database and continue with the connection string provided (for now).
3. Delete the Yarn PnP config files along with `.yarn` and `node_modules`
4. Create a `.yarnrc.yml` and add `nodeLinker: node-modules`
5. Reinstall dependencies with yarn.
6. Update the connection string in the `.env` file as follows: `DATABASE_URI=postgres://postgres:password@mydb:5432/postgres`
7. You will need a test stripe environment with 1 sample product added within that store.
8. Update the `docker-compose.yml` as follows:
```yml
version: "3"

services:
  payload:
    container_name: payload
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    container_name: mydb
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
    restart: "always"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
  node_modules:
```
9. Run `docker compose up -d` to start the app and the database.
10. Seed the database
11. Try to buy the Cotton T shirt.

### Payload Version

^2.0.0

### Adapters and Plugins

db-postgres, seo, redirects, stripePlugin, nestedDocs
