### ISSUE TITLE
Docker compose file still points to mongo volume when initializing "website" template with postgres

### ISSUE THREAD

**Issue by ozzythecoder** [payloadcms/payload#8876]
### Describe the Bug

When running a fresh install with `npm create-payload-app@beta`, and selecting the "website" template and postgres database, the generated `docker-compose.yaml` still lists mongo as a service and dependency, rather than postgres. This causes `docker compose up` to run a crashing instance.

```yaml
# docker-compose.yaml
version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
```

Would recommend including this section from the "blank" template:

```yaml
    depends_on:
      - mongo
      # - postgres

  # .......

  # Uncomment the following to use postgres
  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
```

Another option is to include different compose files, but I understand that's probably not super high priority right now. 😅

### Link to the code that reproduces this issue

https://github.com/ozzythecoder/docker-mongo-issue-repro

### Reproduction Steps

- Run `npm create-payload-app@beta`
- Select "website" template
- Select "Postgres" database
- Run `docker compose up`

### Which area(s) are affected? (Select all that apply)

area: templates

### Environment Info

Binaries:
  Node: 22.10.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.12.2
Relevant Packages:
  payload: 3.0.0-beta.119
  next: 15.0.0
  @payloadcms/db-postgres: 3.0.0-beta.119
  @payloadcms/email-nodemailer: 3.0.0-beta.119
  @payloadcms/graphql: 3.0.0-beta.119
  @payloadcms/live-preview: 3.0.0-beta.119
  @payloadcms/live-preview-react: 3.0.0-beta.119
  @payloadcms/next/utilities: 3.0.0-beta.119
  @payloadcms/payload-cloud: 3.0.0-beta.119
  @payloadcms/plugin-form-builder: 3.0.0-beta.119
  @payloadcms/plugin-nested-docs: 3.0.0-beta.119
  @payloadcms/plugin-redirects: 3.0.0-beta.119
  @payloadcms/plugin-search: 3.0.0-beta.119
  @payloadcms/plugin-seo: 3.0.0-beta.119
  @payloadcms/richtext-lexical: 3.0.0-beta.119
  @payloadcms/translations: 3.0.0-beta.119
  @payloadcms/ui/shared: 3.0.0-beta.119
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 12
